In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [ ]:
2+3

In [ ]:
2+3

In [ ]:
6/3

In [ ]:
(3*8)/(2*3)

In [ ]:
log(12)

In [ ]:
sqrt(121)

In [ ]:
x <- 1:10
cat(x)
cat('Mean of x is' ,mean(x)) #cat and print, both can be used for printing
cat('Median of x is' , median(x))#if we are using cat all outputs will be concatenated
cat('Variance of x is', var(x))
cat('Standard Deviation of x is',sd(x))

In [ ]:
cat(x,'\n')
cat('Mean of x is', mean(x),'\n')
cat('Median of x is', median(x),'\n')
cat('Variance of x is', var(x),'\n')
cat('Standard Deviation of x is', sd(x),'\n')

In [ ]:
print(x)
print(paste('Mean of x is', mean(x)))
print(paste('Median of x is',median(x)))
print(paste('Variance of x is',var(x)))
print(paste('Standard Deviation of x is',sd(x)))

In [ ]:
#Creation of character variable
x <- "dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Creation of numerical variable
x <- 23
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Creation of integer variable
x <- 23L
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Crearion of complex variable
x <- 2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
#Creation of logical variables
x <- TRUE
class(x)
typeof(x)
length(x)
attributes(x)

In [ ]:
vector()#an empty 'logical' (the default) vector

In [ ]:
vector("character",length = 5)#a vector of mode 'character' with 5 elements

In [ ]:
character(5)#the same thing, but using constructor directly

In [ ]:
numeric(5)#numeric vector with 5 elements

In [ ]:
logical(5)# logical vector with 5 elements

In [ ]:
x
class(x)

In [ ]:
#integer vector having 5 elements
x<-c(12L,23L,34L,45L,56L)
x
class(x)
length(x)

In [ ]:
#logical vector having 5 elements
y <- c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)

In [ ]:
#character vector having 3 elements
z<-c("Sarah", "Tracy", "John")
z
class(z)
length(z)

In [ ]:
#add element at the end
print("Elements in z before")
z
z<-c(z,"Annette")
print("Elements in Z after adding new element")
z

In [ ]:
# add element at the front
print("Elemets in z before")
z
z<-c("Greg",z)
print("Elements in z after adding new element")
z


In [ ]:
a <- 1:10
a


In [ ]:
seq(from = 1, to =10, by = 0.1)


In [ ]:
1/0

In [ ]:
0/0

In [ ]:
exp(Inf)# e raised to the power infinity is infinity

In [ ]:
exp(-Inf)# e raised to the power of negative infinity is zero

In [ ]:
Inf - Inf

In [ ]:
log(0)

In [ ]:
log(1)

In [ ]:
a <- c(1.7,"a")
a

In [ ]:
b <- c(TRUE,2,3,FALSE)# True is converted to 1 and FALSE value will be converted to 0
b

In [ ]:
c<-c("a",TRUE)#all logical values will be converted to character
c

In [ ]:
as.numeric("1")#conversion from character to numeric

In [ ]:
as.numeric(c("45","66"))

In [ ]:
as.numeric(c("45","66","six"))#invalid conversion,. Missing values will be introduced

In [ ]:
as.character(22)#conversion from numeric to character


In [ ]:
as.character(c(22,34,56))#conversion from numeric to character

In [ ]:
#Example 1
m <- matrix(nrow=2,ncol=2)
m

In [ ]:
dim(m)

In [ ]:
class(m)

In [ ]:
typeof(m)

In [ ]:
#Example 2
m <- matrix(c(1:3))
print('Given matrix is')
print(m)
print('Dimensions (size) of given matrix is ')
print(dim(m))
print('class of given matrix is ')
print(class(m))
print('type of given matrix is')
print(typeof(m))

In [ ]:
a <- matrix(1:6, nrow=2,ncol=3)
print(a)

In [ ]:
m<-1:10 #Creation of a matrix m, Dimensions of matrix are not specified 
print(m) #print the matrix
print(dim(m))# print the dimensions
dim(m) <- c(2,5)#change the dimensions
print(m)#print the matrix
print(dim(m)) # print the dimensions

In [ ]:
my_name <- readline(prompt = "Enter name: ")
my_age <- readline(prompt = "Enter age: ")
#convert character into string
my_age <- as.integer(my_age)
print(paste("Hi,",my_name,"next year you will be", my_age+1,"years old,"))

In [ ]:
w <- readline()
w

In [2]:
#New Lab Date: 14/09/2019

New LAB right before CAT Date: 14/09/2019

In [3]:
#Creation of 5 Data Types
g = 57.5
class(g)
l = as.integer(5)
class(l)
k = 5 + 2i
class(k)
a = 7; b = 6
n = a>b
n
class(n)
o = as.character(57.5)
class(o)

[1] "numeric"

[1] "integer"

[1] "complex"

[1] TRUE

[1] "logical"

[1] "character"

In [4]:
p <- c(5,3,2,1,4)
class(p)

[1] "numeric"

In [5]:
#The above one is an example for a numeric vector with 5 elements


In [8]:
z <- c("Sarah", "Tracy", "John")
z

[1] "Sarah" "Tracy" "John"

Matrices

In [9]:
m <- matrix(nrow = 2, ncol= 2)
m
dim(m)

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

[1] 2 2

In [10]:
a <- matrix(1:7, nrow = 3, ncol = 3)
a

Warning message in matrix(1:7, nrow = 3, ncol = 3):
“data length [7] is not a sub-multiple or multiple of the number of rows [3]”

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    1   
[3,] 3    6    2

Arrays

In [19]:
ar <- array(1:24, dim = c(4,3,2), dim_name = list (c("One","Two","Three","Four"), c("ray","Karl","Mimo"), c("Steve","Mark")))
print(ar)

ERROR: Error in array(1:24, dim = c(4, 3, 2), dim_name = list(c("One", "Two", : unused argument (dim_name = list(c("One", "Two", "Three", "Four"), c("ray", "Karl", "Mimo"), c("Steve", "Mark")))


In [18]:
#Using two vectors of different lengths as input for the array
vec1 <- c(4,3,2)
vec2 <- c(11,12,13,14,15,16)
res <- array (c(vec1,vec2),dim=c(3,3,2))
print(res)

, , 1

     [,1] [,2] [,3]
[1,]    4   11   14
[2,]    3   12   15
[3,]    2   13   16

, , 2

     [,1] [,2] [,3]
[1,]    4   11   14
[2,]    3   12   15
[3,]    2   13   16



In [21]:
#Naming the Array
vec1 <- c(2,4,6)
vec2 <- c(11,12,13,14,15,16)
column.names <- c("COLA","COLB","COLC")
row.names <- c("ROWA","ROWB","ROWC")
matrix.names <- c("MatA","MatB")

res <- array(c(vec1,vec2), dim = c(3,3,2), dimnames = list(column.names, row.names))
print(res)

, , 1

     ROWA ROWB ROWC
COLA    2   11   14
COLB    4   12   15
COLC    6   13   16

, , 2

     ROWA ROWB ROWC
COLA    2   11   14
COLB    4   12   15
COLC    6   13   16



Factors - Only takes the distinct elements 

In [25]:
f = c("Monday","Tuesday","Wednesday","Wednesday","Thursday","Monday")
factorf3 = factor(f)
print(factorf3)

[1] Monday    Tuesday   Wednesday Wednesday Thursday  Monday   
Levels: Monday Thursday Tuesday Wednesday


Data Frames

In [26]:
name <- c("Glen"," Paulson","Praveen","Bhargav","Rushik")
age <- c(20,54,18,18,18)
vehicle <- c("Harley","Enfield","Enfield","KTM","KTM")
g = data.frame(name,age,vehicle)
print(g)

      name age vehicle
1     Glen  20  Harley
2  Paulson  54 Enfield
3  Praveen  18 Enfield
4  Bhargav  18     KTM
5   Rushik  18     KTM


Creation of vectors using functions

In [29]:
vector() #an empty logical vector - the default vector
print(vector())

logical(0)

logical(0)


In [30]:
vector("character", length = 5) #a vector of mode 'character' with 5 elements

[1] "" "" "" "" ""

In [31]:
character(5) #The same thing but by directly using the constructor

[1] "" "" "" "" ""

In [32]:
numeric(5)

[1] 0 0 0 0 0

In [33]:
logical(5) # a logical vector with 5 elements

[1] FALSE FALSE FALSE FALSE FALSE

In [35]:
complex(5)

[1] 0+0i 0+0i 0+0i 0+0i 0+0i

In [36]:
integer(5)

[1] 0 0 0 0 0

Conversion from one data type to another

In [37]:
g = 57.5
class(g)
l = as.integer(5)
class(l)
k = 5 + 2i
class(k)
a = 7; b = 6
n = a>b
n
class(n)
o = as.character(57.5)
class(o)
m = as.numeric(5L)
class(m)
m

[1] "numeric"

[1] "integer"

[1] "complex"

[1] TRUE

[1] "logical"

[1] "character"

[1] "numeric"

[1] 5

In [42]:
g = 57.5
is.numeric(g)
f = c("Monday","Tuesday","Wednesday","Wednesday","Thursday","Monday")
factorf3 = factor(f)
print(factorf3)
is.factor(factorf3)
 l = 5L
is.integer(l)
is.character(l)

[1] TRUE

[1] Monday    Tuesday   Wednesday Wednesday Thursday  Monday   
Levels: Monday Thursday Tuesday Wednesday


[1] TRUE

[1] TRUE

[1] FALSE

In [55]:
x <- c(1,2,3,4,5,6,7,87,8)
print(x[1:3])
y <- list(1,3,5,7,8,9)
print(y[1:4])
z <- matrix(1:8,nrow=3,ncol=2)
print(z)
print (z[3,1])
f = c("Monday","Tuesday","Wednesday","Wednesday","Thursday","Monday")
factorf3 = factor(f)
print(factorf3[4])
m = data.frame (x,y)
print(m)

[1] 1 2 3
[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 5

[[4]]
[1] 7



Warning message in matrix(1:8, nrow = 3, ncol = 2):
“data length [8] is not a sub-multiple or multiple of the number of rows [3]”

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
[1] 3
[1] Wednesday
Levels: Monday Thursday Tuesday Wednesday
   x X1 X3 X5 X7 X8 X9
1  1  1  3  5  7  8  9
2  2  1  3  5  7  8  9
3  3  1  3  5  7  8  9
4  4  1  3  5  7  8  9
5  5  1  3  5  7  8  9
6  6  1  3  5  7  8  9
7  7  1  3  5  7  8  9
8 87  1  3  5  7  8  9
9  8  1  3  5  7  8  9


In [57]:
x <- c(1,2,3,4,5,6,7,87,8)
print(x[1:3])
y <- list(1,3,5,7,8,9)
print(y[1:4])
m = data.frame (x,y)
print(m)
print(m[1,])
z <- matrix(1:8,nrow=3,ncol=2)
print(z)
print(z[,2])

[1] 1 2 3
[[1]]
[1] 1

[[2]]
[1] 3

[[3]]
[1] 5

[[4]]
[1] 7

   x X1 X3 X5 X7 X8 X9
1  1  1  3  5  7  8  9
2  2  1  3  5  7  8  9
3  3  1  3  5  7  8  9
4  4  1  3  5  7  8  9
5  5  1  3  5  7  8  9
6  6  1  3  5  7  8  9
7  7  1  3  5  7  8  9
8 87  1  3  5  7  8  9
9  8  1  3  5  7  8  9
  x X1 X3 X5 X7 X8 X9
1 1  1  3  5  7  8  9


Warning message in matrix(1:8, nrow = 3, ncol = 2):
“data length [8] is not a sub-multiple or multiple of the number of rows [3]”

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
[1] 4 5 6


In [67]:
name <- c("Glen"," Paulson","Praveen","Bhargav","Rushik")
age <- c(20,54,18,18,18)
vehicle <- c("Harley","Enfield","Enfield","KTM","KTM")
g = data.frame(name,age,vehicle)
print(g)
#Adding columns in the data frame
g$sex = c('m','m','m','m','m')
print(g)
#Adding Rows in the data frame
name <- c("Jaleena")
age <- c(20)
vehicle <- c("Lamborgini")
sex <- c('f')
print(g)
frame1 <- data.frame(name,age,vehicle,sex)
framefinal <- rbind(g,frame1)
print(framefinal)

      name age vehicle
1     Glen  20  Harley
2  Paulson  54 Enfield
3  Praveen  18 Enfield
4  Bhargav  18     KTM
5   Rushik  18     KTM
      name age vehicle sex
1     Glen  20  Harley   m
2  Paulson  54 Enfield   m
3  Praveen  18 Enfield   m
4  Bhargav  18     KTM   m
5   Rushik  18     KTM   m
      name age vehicle sex
1     Glen  20  Harley   m
2  Paulson  54 Enfield   m
3  Praveen  18 Enfield   m
4  Bhargav  18     KTM   m
5   Rushik  18     KTM   m
      name age    vehicle sex
1     Glen  20     Harley   m
2  Paulson  54    Enfield   m
3  Praveen  18    Enfield   m
4  Bhargav  18        KTM   m
5   Rushik  18        KTM   m
6  Jaleena  20 Lamborgini   f
