In [30]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

ERROR: Error in parse(text = x, srcfile = src): <text>:5:8: unexpected symbol
4: 
5: import numpy
          ^


In [71]:
2+3

[1] 5

In [72]:
2+3

[1] 5

In [73]:
6/3

[1] 2

In [74]:
(3*8)/(2*3)

[1] 4

In [75]:
log(12)

[1] 2.484907

In [76]:
sqrt(121)

[1] 11

In [77]:
x <- 1:10
cat(x)
cat('Mean of x is' ,mean(x)) #cat and print, both can be used for printing
cat('Median of x is' , median(x))#if we are using cat all outputs will be concatenated
cat('Variance of x is', var(x))
cat('Standard Deviation of x is',sd(x))

1 2 3 4 5 6 7 8 9 10Mean of x is 5.5Median of x is 5.5Variance of x is 9.166667Standard Deviation of x is 3.02765

In [78]:
cat(x,'\n')
cat('Mean of x is', mean(x),'\n')
cat('Median of x is', median(x),'\n')
cat('Variance of x is', var(x),'\n')
cat('Standard Deviation of x is', sd(x),'\n')

1 2 3 4 5 6 7 8 9 10 
Mean of x is 5.5 
Median of x is 5.5 
Variance of x is 9.166667 
Standard Deviation of x is 3.02765 


In [79]:
print(x)
print(paste('Mean of x is', mean(x)))
print(paste('Median of x is',median(x)))
print(paste('Variance of x is',var(x)))
print(paste('Standard Deviation of x is',sd(x)))

 [1]  1  2  3  4  5  6  7  8  9 10
[1] "Mean of x is 5.5"
[1] "Median of x is 5.5"
[1] "Variance of x is 9.16666666666667"
[1] "Standard Deviation of x is 3.02765035409749"


In [80]:
#Creation of character variable
x <- "dataset"
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [81]:
#Creation of numerical variable
x <- 23
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "numeric"

[1] "double"

[1] 1

NULL

In [82]:
#Creation of integer variable
x <- 23L
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "integer"

[1] "integer"

[1] 1

NULL

In [83]:
#Crearion of complex variable
x <- 2+3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [84]:
#Creation of logical variables
x <- TRUE
class(x)
typeof(x)
length(x)
attributes(x)

[1] "logical"

[1] "logical"

[1] 1

NULL

In [85]:
vector()#an empty 'logical' (the default) vector

logical(0)

In [86]:
vector("character",length = 5)#a vector of mode 'character' with 5 elements

[1] "" "" "" "" ""

In [87]:
character(5)#the same thing, but using constructor directly

[1] "" "" "" "" ""

In [88]:
numeric(5)#numeric vector with 5 elements

[1] 0 0 0 0 0

In [89]:
logical(5)# logical vector with 5 elements

[1] FALSE FALSE FALSE FALSE FALSE

In [90]:
x
class(x)

[1] TRUE

[1] "logical"

In [91]:
#integer vector having 5 elements
x<-c(12L,23L,34L,45L,56L)
x
class(x)
length(x)

[1] 12 23 34 45 56

[1] "integer"

[1] 5

In [92]:
#logical vector having 5 elements
y <- c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)

[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [93]:
#character vector having 3 elements
z<-c("Sarah", "Tracy", "John")
z
class(z)
length(z)

[1] "Sarah" "Tracy" "John"

[1] "character"

[1] 3

In [94]:
#add element at the end
print("Elements in z before")
z
z<-c(z,"Annette")
print("Elements in Z after adding new element")
z

[1] "Elements in z before"


[1] "Sarah" "Tracy" "John"

[1] "Elements in Z after adding new element"


[1] "Sarah"   "Tracy"   "John"    "Annette"

In [34]:
# add element at the front
print("Elemets in z before")
z
z<-c("Greg",z)
print("Elements in z after adding new element")
z


[1] "Elemets in z before"


[1] "Sarah"   "Tracy"   "John"    "Annette"

[1] "Elements in z after adding new element"


[1] "Greg"    "Sarah"   "Tracy"   "John"    "Annette"

In [35]:
a <- 1:10
a


[1]  1  2  3  4  5  6  7  8  9 10

In [36]:
seq(from = 1, to =10, by = 0.1)


[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

In [37]:
1/0

[1] Inf

In [38]:
0/0

[1] NaN

In [39]:
exp(Inf)# e raised to the power infinity is infinity

[1] Inf

In [40]:
exp(-Inf)# e raised to the power of negative infinity is zero

[1] 0

In [41]:
Inf - Inf

[1] NaN

In [42]:
log(0)

[1] -Inf

In [44]:
log(1)

[1] 0

In [47]:
a <- c(1.7,"a")
a

[1] "1.7" "a"

In [50]:
b <- c(TRUE,2,3,FALSE)# True is converted to 1 and FALSE value will be converted to 0
b

[1] 1 2 3 0

In [53]:
c<-c("a",TRUE)#all logical values will be converted to character
c

[1] "a"    "TRUE"

In [54]:
as.numeric("1")#conversion from character to numeric

[1] 1

In [55]:
as.numeric(c("45","66"))

[1] 45 66

In [56]:
as.numeric(c("45","66","six"))#invalid conversion,. Missing values will be introduced

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 66 NA

In [57]:
as.character(22)#conversion from numeric to character


[1] "22"

In [58]:
as.character(c(22,34,56))#conversion from numeric to character

[1] "22" "34" "56"

In [59]:
#Example 1
m <- matrix(nrow=2,ncol=2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [60]:
dim(m)

[1] 2 2

In [61]:
class(m)

[1] "matrix"

In [63]:
typeof(m)

[1] "logical"

In [64]:
#Example 2
m <- matrix(c(1:3))
print('Given matrix is')
print(m)
print('Dimensions (size) of given matrix is ')
print(dim(m))
print('class of given matrix is ')
print(class(m))
print('type of given matrix is')
print(typeof(m))

[1] "Given matrix is"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "Dimensions (size) of given matrix is "
[1] 3 1
[1] "class of given matrix is "
[1] "matrix"
[1] "type of given matrix is"
[1] "integer"


In [65]:
a <- matrix(1:6, nrow=2,ncol=3)
print(a)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [67]:
m<-1:10 #Creation of a matrix m, Dimensions of matrix are not specified 
print(m) #print the matrix
print(dim(m))# print the dimensions
dim(m) <- c(2,5)#change the dimensions
print(m)#print the matrix
print(dim(m)) # print the dimensions

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


In [69]:
my_name <- readline(prompt = "Enter name: ")
my_age <- readline(prompt = "Enter age: ")
#convert character into string
my_age <- as.integer(my_age)
print(paste("Hi,",my_name,"next year you will be", my_age+1,"years old,"))

Enter name: Glen
Enter age: 20
[1] "Hi, Glen next year you will be 21 years old,"


In [70]:
w <- readline()
w

hello


[1] "hello"